### ISSUE TITLE
TODO/FIXME Count 34

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-web-profile-manager#32]
- [ ] FIXME: Do not introsepect url to get the Keystore ID
       Commit: (49db73d) Add fixme.
       File:  [utils.js:256](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L256)
       Ganesh Annan commented 2 months ago

  - [ ] TODO: map `signer.type` to signature suite
       Commit: (a453e94) wip
       File:  [utils.js:244](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L244)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (51e8df2) Enable delegation revocations.
       File:  [utils.js:219](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L219)
       Ganesh Annan commented 2 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (a453e94) wip
       File:  [utils.js:201](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L201)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (51e8df2) Enable delegation revocations.
       File:  [utils.js:181](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L181)
       Ganesh Annan commented 2 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (a453e94) wip
       File:  [utils.js:161](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L161)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: note that only the recipient of the zcap will be able
       Commit: (a453e94) wip
       File:  [utils.js:139](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L139)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (a453e94) wip
       File:  [utils.js:137](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L137)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: this is not clean; zcap query needs work! ... another
       Commit: (a453e94) wip
       File:  [utils.js:104](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L104)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (a453e94) wip
       File:  [utils.js:92](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L92)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: fetch `target` from a key mapping document in the profile's
       Commit: (a453e94) wip
       File:  [utils.js:74](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L74)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: make finding parent capability chain more robust
       Commit: (bb1ddbc) Fix more zcap chain building bugs.
       File:  [utils.js:56](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L56)
       Dave Longley commented 3 months ago

  - [ ] TODO: Look into requiring an invoker or controller on a zcap
       Commit: (a453e94) wip
       File:  [utils.js:29](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/utils.js#L29)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: could be made more restrictive is based on a config option that
       Commit: (a453e94) wip
       File:  [keyResolver.js:9](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/keyResolver.js#L9)
       Ganesh Annan commented 4 months ago

  - [ ] FIXME: make more restrictive, support `did:key` and `did:v1`
       Commit: (a453e94) wip
       File:  [keyResolver.js:8](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/keyResolver.js#L8)
       Ganesh Annan commented 4 months ago

  - [ ] FIXME: simplify reference ID for this; force only one reference ID
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:901](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L901)
       Dave Longley commented 3 months ago

  - [ ] TODO: delegate this on demand instead, being careful not to create
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:820](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L820)
       Dave Longley commented 3 months ago

  - [x] TODO: add cache (ensure cache gets cleared when session changes or
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:755](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L755)
       Dave Longley commented 3 months ago

  - [x] TODO: support N capability agents, one per profile/profile-agent
       Commit: (6c91526) Generate a new secret on session change.
       File:  [ProfileManager.js:748](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L748)
       Matthew Collier commented 3 months ago

  - [ ] TODO: consider storing indexes for profile EDVs in the profile's
       Commit: (ff99c62) Add TODO.
       File:  [ProfileManager.js:688](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L688)
       Dave Longley commented 3 months ago

  - [ ] FIXME: remove exposure of this?
       Commit: (ff99c62) Add TODO.
       File:  [ProfileManager.js:650](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L650)
       Dave Longley commented 3 months ago

  - [ ] TODO: validate `parentCapabilities`
       Commit: (ef1b6d3) Move `delegateEdvCapabilities` to profile manager and fix bugs.
       File:  [ProfileManager.js:556](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L556)
       Dave Longley commented 3 months ago

  - [ ] TODO: consider consolidation with `getProfileEdv`
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:487](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L487)
       Dave Longley commented 3 months ago

  - [ ] FIXME: expose this or not?
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:464](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L464)
       Dave Longley commented 3 months ago

  - [ ] FIXME: getting the keystore for the profile should involve reading the
       Commit: (ef1b6d3) Move `delegateEdvCapabilities` to profile manager and fix bugs.
       File:  [ProfileManager.js:452](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L452)
       Dave Longley commented 3 months ago

  - [ ] TODO: Use proper promise-fun library to limit concurrency
       Commit: (a453e94) wip
       File:  [ProfileManager.js:442](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L442)
       Ganesh Annan commented 4 months ago

  - [ ] TODO: implement on demand delegation; if agent has a zcap for using
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:408](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L408)
       Dave Longley commented 3 months ago

  - [ ] TODO: cache profile signer by profile ID?
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:369](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L369)
       Dave Longley commented 3 months ago

  - [ ] TODO: note that `user-edv-kak` will be duplicated here -- future
       Commit: (ef1b6d3) Move `delegateEdvCapabilities` to profile manager and fix bugs.
       File:  [ProfileManager.js:277](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L277)
       Dave Longley commented 3 months ago

  - [ ] TODO: once delegate on demand is implemented for agents with that
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:275](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L275)
       Dave Longley commented 3 months ago

  - [ ] TODO: once delegate on demand is implemented for agents with that
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:265](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L265)
       Dave Longley commented 3 months ago

  - [x] TODO: handle case where capability is missing
       Commit: (f8e81f9) Rework APIs.
       File:  [ProfileManager.js:226](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L226)
       Dave Longley commented 3 months ago

  - [ ] TODO: check authority model on this
       Commit: (f8e81f9) Rework APIs.
       File:  [AccessManager.js:135](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/AccessManager.js#L135)
       Dave Longley commented 3 months ago

  - [ ] TODO: handle removal of self
       Commit: (f8e81f9) Rework APIs.
       File:  [AccessManager.js:131](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/AccessManager.js#L131)
       Dave Longley commented 3 months ago

       FIXME Count         6
       TODO Count          28
       Oldest Comment      4 months ago
       Oldest Commenter    Ganesh Annan
       Oldest Comment      TODO: map `signer.type` to signature suite

**Comment by mandyvenables** [comment]
@dlongley @gannan08 Are any of these priorities?

**Comment by dlongley** [comment]
Closing this as addressed or split into other issues.
