### ISSUE TITLE
FIXME Count 6 / TODO Count 32

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile-manager#5]
- [ ] FIXME: make more restrictive, support `did:key` and `did:v1`
       Commit: (3066b89) Pass `keyResolver` to data hub client.
       File:  [ProfileManager.js:601](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L601)
       Dave Longley commented 6 months ago

  - [ ] TODO: map `signer.type` to signature suite
       Commit: (f525756) Add `delegateCapability` function.
       File:  [ProfileManager.js:569](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L569)
       Dave Longley commented 7 months ago

  - [ ] TODO: updating profile edvs should not be required once profile
       Commit: (a7cb5f4) Use webkms-client, edv-client, and update dependencies.
       File:  [ProfileManager.js:549](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L549)
       Dave Longley commented a month ago

  - [ ] FIXME: this needs to be posted to a different endpoint that is
       Commit: (3e83819) Add FIXME.
       File:  [ProfileManager.js:527](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L527)
       Dave Longley commented 5 months ago

  - [ ] TODO: handle future case where user has not authorized the
       Commit: (58b8276) Support keystore recovery on session change.
       File:  [ProfileManager.js:474](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L474)
       Dave Longley commented 5 months ago

  - [ ] TODO: add `invoker` and `delegator` using controllerKey.id *or*, if
       Commit: (2dc2ca4) Include `invocationSigner` when using data hubs.
       File:  [ProfileManager.js:408](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L408)
       Dave Longley commented 7 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (b753dcd) Add ability to delegate delegatable zcaps.
       File:  [ProfileManager.js:339](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L339)
       Dave Longley commented 5 days ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (79caaae) Add support for edv document collection and authorization zcaps.
       File:  [ProfileManager.js:318](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L318)
       Dave Longley commented 7 days ago

  - [ ] TODO: note that only the recipient of the zcap will be able
       Commit: (79caaae) Add support for edv document collection and authorization zcaps.
       File:  [ProfileManager.js:296](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L296)
       Dave Longley commented 7 days ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (79caaae) Add support for edv document collection and authorization zcaps.
       File:  [ProfileManager.js:294](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L294)
       Dave Longley commented 7 days ago

  - [ ] TODO: this is not clean; zcap query needs work! ... another
       Commit: (c78605e) Create datahub doc including recipient when access is requested.
       File:  [ProfileManager.js:262](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L262)
       Dave Longley commented 6 months ago

  - [ ] TODO: handle case where an existing target is requested
       Commit: (c78605e) Create datahub doc including recipient when access is requested.
       File:  [ProfileManager.js:251](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L251)
       Dave Longley commented 6 months ago

  - [ ] TODO: put public key ID here
       Commit: (f525756) Add `delegateCapability` function.
       File:  [ProfileManager.js:236](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L236)
       Dave Longley commented 7 months ago

  - [ ] TODO: fetch `target` from a key mapping document in the profile's
       Commit: (f525756) Add `delegateCapability` function.
       File:  [ProfileManager.js:231](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L231)
       Dave Longley commented 7 months ago

  - [ ] TODO: to reduce correlation between the account and multiple profiles,
       Commit: (f525756) Add `delegateCapability` function.
       File:  [ProfileManager.js:200](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L200)
       Dave Longley commented 7 months ago

  - [ ] TODO: implement adding an existing profile to an account
       Commit: (7227f17) Add core files.
       File:  [ProfileManager.js:157](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L157)
       Dave Longley commented 9 months ago

  - [ ] TODO: might need this to be the specific document -- or a zcap
       Commit: (b8ed35d) Update to latest data hub and kms APIs.
       File:  [ProfileManager.js:144](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L144)
       Dave Longley commented 7 months ago

  - [ ] TODO: support making the profile edv controlled by the profile
       Commit: (a7cb5f4) Use webkms-client, edv-client, and update dependencies.
       File:  [ProfileManager.js:124](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L124)
       Dave Longley commented a month ago

  - [ ] FIXME: add support for key generation via webkms-client, invoke key
       Commit: (954046b) Remove bedrock-web-did-store usage.
       File:  [ProfileManager.js:118](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L118)
       Dave Longley commented 12 days ago

       FIXME Count         6
       TODO Count          32
       Oldest Comment      9 months ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: implement adding an existing profile to an account

**Comment by mandyvenables** [comment]
New version: https://github.com/digitalbazaar/bedrock-web-profile-manager/issues/32
